### ISSUE TITLE
ShouldBeFail throws a MissingMethodException

### ISSUE THREAD

**Issue by ghost** [yuriylsh/LanguageExt.UnitTesting#11]
Hi,

I recently had to change how my tests check for Fin failures after the LanguageExt.Core package took the IEnumerable interface from the Fin class.  I tried using the Fin Extension ShouldBeFail but I get a MissingMethodException.  I have a small project to reproduce the problem using a unit test.  Can you please advise me if this is a bug or if I'm using the assertion incorrectly?
[Language.Ext.UnitTests.zip](https://github.com/user-attachments/files/16073768/Language.Ext.UnitTests.zip)

Thanks

**Comment by ghost** [comment]
I was able to attempt some more trial and error with my sample app and found that if I remove the LanguageExt.Core nuget package the test runs fine.  This points to a mismatch between the version of LanguageExt.Core in LanguageExt.UnitTesting (v3.4.0) and LanguageExt.Core (v4.4.9).  I'm not sure this is an option for my production solution as I need a reference to LanguageExt.Core in some projects and LanguageExt.UnitTesting in my test projects.  Can these libraries be synced soon?

One more note:  The exception starts throwing when I switch from LanguageExt.Core v4.29 to v4.4.0.

**Comment by yuriylsh** [comment]
@bradj23 tank you for bringing it to my attention. The version has been upgraded to 4.4.9

**Comment by ghost** [comment]
Thanks for the quick response, @yuriylsh.  I updated both packages to 4.4.9 but I'm still getting a MissingMethodException.  I did notice the assembly version hasn't change. I'm not sure if that would cause confusion.  I can post my latest sample if that would help.

// Decompiled with JetBrains decompiler
// Type: LanguageExt.UnitTesting.FinExtensions
// Assembly: LanguageExt.UnitTesting, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 3121DD0C-8885-4CA3-8DF8-CF7DD42E2B2F
// Assembly location: nuget\packages\languageext.unittesting\4.4.9\lib\netstandard2.0\LanguageExt.UnitTesting.dll

**Comment by yuriylsh** [comment]
@bradj23 Thank you for the feedback! My bad, I did not verify the package. I've unlisted the 4.4.9 version and the new 4.4.9.1 version should be live on Nuget now

**Comment by ghost** [comment]
That fixed my tests!  Thanks again for responding so quickly and working with me.
