### ISSUE TITLE
Added to lang-ext wiki

### ISSUE THREAD

**Issue by louthy** [yuriylsh/LanguageExt.UnitTesting#8]
Hi @yuriylsh, I have added this project to the lang-ext wiki: https://github.com/louthy/language-ext/wiki

If you feel like you'd rather not have the attention, please let me know and I'll remove it.

Good work on the project, it looks great!

**Comment by yuriylsh** [comment]
Hi @louthy , I don't mind the mentioning in the wiki at all. I enjoy using language-ext and appreciate the effort you put into creating and maintaining it!
