### ISSUE TITLE
Assert.Equals should not be used for Assertions. Please use Assert.AreEqual & overloads instead

### ISSUE THREAD

**Issue by MrYossu** [yuriylsh/LanguageExt.UnitTesting#9]
Not sure if this problem is because I'm using MsTest not Xunit, but I have the following...

```
    [TestMethod]
    public void Investor_CurrentTerm_OneForTheCurrentDate() {
      Investor investor = new() {
        Terms = new List<Term> {
          new() { Start = new(2020, 1, 1), End = new(2020, 12, 31) }
        }
      };
      Option<Term> term = investor.CurrentTerm(_date);
      term.ShouldBeSome(t => Assert.Equals(new DateTime(2020, 1, 1), t.Start));
    }
```

However, this fails with the message shown above, even though this is how you show the test on the main project page. You own unit tests don't seem to do this kind of test, so no help there.

If I change the last line to...

    term.ShouldBeSome(t => Assert.AreEqual(new DateTime(2020, 1, 1), t.Start));

...then the test is inconclusive.

How do I test this?

**Comment by yuriylsh** [comment]
> However, this fails with the message shown above

Unfortunately your question does not include the message (edit: sorry, just realized the error is in the title 😳 ) , so I can only assume it fails with the following error: 
```
Assert.Fail failed. Assert.Equals should not be used for Assertions. Please use Assert.AreEqual & overloads instead.
```
As you rightfully noticed that it [needs to be changed](https://github.com/microsoft/testfx/blob/7de14c4045dcec4e0f100c5925c007c28613a6f4/src/TestFramework/MSTest.Core/Assertions/Assert.cs#L2023) to `Assert.AreEqual` and at this point it should work as far as I can tell:
![image](https://user-images.githubusercontent.com/429047/105580621-14f1ed00-5d53-11eb-8ff3-9706a9f38593.png)



Here is code for the repro: https://gist.github.com/yuriylsh/5c099d81c33111b05195bf6ad60e683f

Let me know if you still have issues with the test.

**Comment by MrYossu** [comment]
Hmm, odd. I just tried again (same code) and it works fine now!

Thanks
